/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseCodeRouteImport } from './routes/courses.$courseCode'

const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseCodeRoute = CoursesCourseCodeRouteImport.update({
  id: '/$courseCode',
  path: '/$courseCode',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/grades': typeof GradesRoute
  '/manual': typeof ManualRoute
  '/preferences': typeof PreferencesRoute
  '/courses/$courseCode': typeof CoursesCourseCodeRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grades': typeof GradesRoute
  '/manual': typeof ManualRoute
  '/preferences': typeof PreferencesRoute
  '/courses/$courseCode': typeof CoursesCourseCodeRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/grades': typeof GradesRoute
  '/manual': typeof ManualRoute
  '/preferences': typeof PreferencesRoute
  '/courses/$courseCode': typeof CoursesCourseCodeRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/grades'
    | '/manual'
    | '/preferences'
    | '/courses/$courseCode'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grades'
    | '/manual'
    | '/preferences'
    | '/courses/$courseCode'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/grades'
    | '/manual'
    | '/preferences'
    | '/courses/$courseCode'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  GradesRoute: typeof GradesRoute
  ManualRoute: typeof ManualRoute
  PreferencesRoute: typeof PreferencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseCode': {
      id: '/courses/$courseCode'
      path: '/$courseCode'
      fullPath: '/courses/$courseCode'
      preLoaderRoute: typeof CoursesCourseCodeRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesCourseCodeRoute: typeof CoursesCourseCodeRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseCodeRoute: CoursesCourseCodeRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  GradesRoute: GradesRoute,
  ManualRoute: ManualRoute,
  PreferencesRoute: PreferencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
